### ISSUE TITLE
6to5 with undefined require

### ISSUE THREAD

**Issue by joshbedo** [gobblejs/gobble#32]
So I'm trying to setup gobble with 6to5 and pretty confused on how to get it working properly. My gobble file is fine and handling the transpiling. I have an `index.html` where i load `requirejs` via bower and then load `app.js` which is the transpiled version coming from `http://localhost:4567`. I see `require is not defined` when i exclude `requirejs`. I see `require.js:174 Uncaught Error: Module name "test" has not been loaded yet for context: _. Use require([])` when I load `app.js` from localhost with requirejs. 

a) should i be loading `index.html` file from my filesystem and connecting to assets via gobble localhost? or should i have it within the localhost gobble generates.
b) Is `requirejs` required for the `require` definition?
c) what is a good practice because i couldn't find much information on a proper setup.

Thanks!

**Comment by Rich-Harris** [comment]
6to5 only handles the ES6 -> ES5 module part - you still need a way to load the generated ES5 modules, which is what RequireJS provides. But 6to5 needs to generate AMD modules for that to work - by the sounds of that `Module name "test" has not been loaded yet for context` message, it's currently generating CommonJS (i.e. node) modules, is that right? (In CommonJS, `require('someModule')` is synchronous. The semantics of AMD modules are very different, I won't get into it here as it'll turn into a long and boring essay.)

[Here](https://github.com/Rich-Harris/example-gobble-6to5) is an example of using 6to5 to generate AMD modules, and RequireJS to load them in. The [with-optimizer](https://github.com/Rich-Harris/example-gobble-6to5/tree/with-optimizer) branch demonstrates using the [RequireJS optimizer](http://requirejs.org/docs/optimization.html) to go one step further and bundle the modules into a single file, to eliminate unnecessary HTTP requests.

It's possible to eliminate RequireJS altogether by turning the optimized bundle into a self-executing script, using something like [AMDClean](https://github.com/gfranko/amdclean/). That saves you >15kb and one HTTP request. An example of that is in the [with-amdclean](https://github.com/Rich-Harris/example-gobble-6to5/tree/with-amdclean) branch.

An even better alternative, in my view, is to use Browserify, which can create a self-executing bundle. This allows you to use any node modules you've installed with `npm install` - the main appeal of this is that you don't need to use Bower. Bower is pretty terrible in my opinion, and having two separate package managers is no fun. An example of this setup is in the [with-browserify](https://github.com/Rich-Harris/example-gobble-6to5/tree/with-browserify) branch.

To answer the questions directly...

1. Typically your `index.html` file would be part of your build definition (i.e. served by gobble). It's not a great idea to have `<script src='http://localhost:4567/app.js'></script>` or whatever, because then your app isn't portable - relative URLs are always better. As a general rule, if it's part of your app, it should be in your build definition.
2. Yes. In the future, browsers will have their own module loading capability, but for now RequireJS is basically your best option (though [system.js](https://github.com/systemjs/systemjs) is worth checking out). 
3. Gobble definitely needs some more example set-ups. It's not quite 'done' yet, and I haven't had as much time to work on it as I would have liked, but this is a big TODO. Thanks for helping me get the ball rolling :)

Hope this helps - I know from personal experience that this module stuff is finicky and confusing until you have a set-up that works well for you.

**Comment by joshbedo** [comment]
Thanks for the awesome elaborate response :)
