### ISSUE TITLE
Build destination question

### ISSUE THREAD

**Issue by matthewspencer** [gobblejs/gobble#85]
Getting started with Gobble (coming from both Gulp and Grunt), I have a question about the path used for dest param in the watch task. My goal here is to rewrite this [gulpfile.js](https://github.com/athletics/AdManager/blob/master/gulpfile.js), which uses RequireJS to wrap up UMD modules. Included below is my first pass for the gobblefile.js replacement.

```javascript
var gobble = require( 'gobble' );

module.exports = gobble( './' ).transform( 'requirejs', {
    name: './src/Index',
    out: './dist/AdManager.js',
    optimize: 'none',
    paths: {
        jquery: 'empty:'
    }
} );
```

I tried setting the dest to the current directory:

```bash
gobble watch ./
```

But very bad things happened.

So my question is, what should the dest path be set to in this use case?

**Comment by evs-chris** [comment]
I'm not entirely sure how requirejs works, as I've not used it, but it looks like what you're doing there will change a file nested in the cwd as a result of the build. And that will trigger a rebuild, and so forth until the singularity. My guess would be that you can drop the path `./dist/` off of the out param and gobble will use one of its build paths instead of the cwd and that will stop the build from looping triggering itself.

**Comment by matthewspencer** [comment]
Thanks @evs-chris! That makes total sense. I’m going to close this issue, but I wanted to include the changes below for posterity.

gobblefile.js:

```javascript
var gobble = require( 'gobble' );

module.exports = gobble( './' ).transform( 'requirejs', {
    name: './src/Index',
    out: './AdManager.js',
    optimize: 'none',
    paths: {
        jquery: 'empty:'
    }
} );
```

watch path in the cli:

```bash
gobble watch dist
```
